# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl {
  {D:/Profiles/Administrator/Desktop/v2/3430 project v2/v2/project_1/project_1.srcs/sources_1/new/debounce.vhd}
  {D:/Profiles/Administrator/Desktop/v2/3430 project v2/v2/project_1/project_1.srcs/sources_1/new/v2.vhd}
}
read_xdc {{D:/Profiles/Administrator/Desktop/v2/3430 project v2/v2/project_1/project_1.srcs/constrs_1/new/v2xdc.xdc}}
set_property used_in_implementation false [get_files {{D:/Profiles/Administrator/Desktop/v2/3430 project v2/v2/project_1/project_1.srcs/constrs_1/new/v2xdc.xdc}}]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Profiles/Administrator/Desktop/v2/3430 project v2/v2/project_1/project_1.data/wt} [current_project]
set_property parent.project_dir {D:/Profiles/Administrator/Desktop/v2/3430 project v2/v2/project_1} [current_project]
synth_design -top v1 -part xc7z020clg484-1
write_checkpoint v1.dcp
report_utilization -file v1_utilization_synth.rpt -pb v1_utilization_synth.pb
